CREATE TABLE [dbo].[Ciudad]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[nombre] VARCHAR(30) NOT NULL, 
	[idEstado] INT NOT NULL FOREIGN KEY REFERENCES Estado(id) ON DELETE CASCADE ON UPDATE CASCADE
)
