CREATE TABLE [dbo].[Anuncio_Paquete]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[idAnuncio] INT NOT NULL FOREIGN KEY REFERENCES Anuncio(id) ON DELETE CASCADE ON UPDATE CASCADE, 
	[idPaquete] INT NOT NULL FOREIGN KEY REFERENCES Paquete(id) ON DELETE NO ACTION ON UPDATE CASCADE, 
	[fechaInicio] DATE NOT NULL, 
	[fechaFin] DATE NOT NULL, 
	[activo] BIT NOT NULL,
	[folio] VARCHAR(20) NOT NULL
)
