CREATE TABLE [dbo].[Pago_Concepto]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[idPago] INT NOT NULL FOREIGN KEY REFERENCES Pago(id) ON DELETE CASCADE ON UPDATE CASCADE, 
	[idPaquete] INT FOREIGN KEY REFERENCES Paquete(id) ON DELETE NO ACTION ON UPDATE CASCADE, 
	[idBeneficio] INT FOREIGN KEY REFERENCES Beneficio(id) ON DELETE NO ACTION ON UPDATE CASCADE, 
	[tipo] BIT NOT NULL
)
