CREATE TABLE [dbo].[Pago_Concepto]
(
	[id] INT NOT NULL PRIMARY KEY, 
	[idPago] INT NOT NULL FOREIGN KEY REFERENCES Pago(id) ON DELETE CASCADE ON UPDATE CASCADE, 
	[idPlazo] INT FOREIGN KEY REFERENCES Plazo(id) ON DELETE NO ACTION ON UPDATE CASCADE, 
	[idBeneficio] INT FOREIGN KEY REFERENCES Beneficio(id) ON DELETE NO ACTION ON UPDATE CASCADE, 
	[tipo] BIT NOT NULL
)
